# Generated by Django 6.0 on 2025-12-13 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
